configs:
  cm:
    url: https://argocd.lab0.sikademo.com
    exec.enabled: "true"
    oidc.config: |
      name: SSO
      issuer: https://sso.lab0.sikademo.com/realms/kcd
      clientID: argocd
      clientSecret: argocd_secret
      requestedScopes: ["openid", "profile", "email", "groups"]
      logoutURL: "https://sso.lab0.sikademo.com/realms/kcd/protocol/openid-connect/logout?client_id=example_client_id&id_token_hint={{token}}&post_logout_redirect_uri=https://argocd.lab0.sikademo.com"
  rbac:
    scopes: '[groups]'
    policy.default: ""
    policy.csv: |
      g, argocd-admin, role:admin
      g, argocd-ro, role:readonly
server:
  ingress:
    enabled: true
    hostname: argocd.lab0.sikademo.com
    tls: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
