apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-sso
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hello-sso
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/one-image
    helm:
      releaseName: oauth2-proxy-ondrej-example
      values: |
        host: hello-sso.lab0.sikademo.com
        image: sikalabs/hello-world-server
        containerPort: 8000
        ingressExtraAnnotations:
          nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.lab0.sikademo.com/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.lab0.sikademo.com/oauth2/start?rd=https://hello-sso.lab0.sikademo.com"
          nginx.ingress.kubernetes.io/proxy-body-size: 512m
          nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
