# https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml
# https://artifacthub.io/packages/helm/bitnami/keycloak?modal=values
replicaCount: 1
proxy: edge
global:
  security:
    allowInsecureImages: true
image:
  registry: ghcr.io
  repository: sikalabs/bitnami-keycloak-sikalabs-theme
  tag: 25.0.5-debian-12-r1
  pullPolicy: Always
auth:
  createAdminUser: true
  adminUser: admin
  adminPassword: admin
  managementUser: manager
  managementPassword: manager
proxyAddressForwarding: true
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: sso.labX.sikademo.com
  tls: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 250m
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    cert-manager.io/cluster-issuer: letsencrypt
postgresql:
  auth:
    postgresPassword: pg
    password: pg
